{
  "name": "all",
  "on": {
    "push": {
      "paths-ignore": [
        "readme.md",
        "LICENSE"
      ]
    },
    "pull_request": {
      "paths-ignore": [
        "readme.md",
        "LICENSE"
      ]
    }
  },
  "jobs": {
    "build": {
      "runs-on": "windows-latest",
      "steps": [
        {
          "name": "checkout",
          "uses": "actions/checkout@v3"
        },
        {
          "name": "build",
          "run": "./build.ps1"
        }
      ]
    },
    "release": {
      "name": "Create GitHub Release",
      "needs": "build",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "runs-on": "windows-latest",
      "steps": [
        {
          "name": "checkout",
          "uses": "actions/checkout@v3",
          "with": {
            "fetch-depth": 0
          }
        },
        {
          "name": "build and package",
          "run": "./.github/scripts/build.ps1 -outDir ./build"
        },
        {
          "name": "create github release",
          "env": {
            "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
          },
          "run": "gh release create ${{ github.ref_name }} (Get-ChildItem -recurse -file ./build/) --generate-notes --title ${{ github.ref_name }}"
        }
      ]
    }
  }
}
